# Exploratory Data Analysis and Insights on Titanic Passenger Survival Using Pandas

### Beginner-Level Pandas Practice Notebook

This notebook is designed for candidates who are currently learning the basics of **Pandas**.  
The exercises focus on simple data inspection, selection, filtering, missing-value checking, string operations, and basic DataFrame manipulation.

## About the Dataset

The **train.csv** dataset contains information about passengers who travelled on the RMS Titanic and whether each passenger survived the sinking.

**Source:** Kaggle - Titanic - Machine Learning from Disaster (https://www.kaggle.com/c/titanic). Use the `train.csv` file.

The dataset contains:

- **891 rows**
- **12 columns**
- **Missing values are present** in a few columns (such as `Age`, `Cabin` and `Embarked`)

### Columns in the Dataset

| Column | Description |
|---|---|
| `PassengerId` | Unique ID of the passenger |
| `Survived` | 0 = did not survive, 1 = survived |
| `Pclass` | Ticket class (1 = 1st, 2 = 2nd, 3 = 3rd) |
| `Name` | Passenger name |
| `Sex` | Gender of the passenger |
| `Age` | Age in years |
| `SibSp` | Number of siblings / spouses aboard |
| `Parch` | Number of parents / children aboard |
| `Ticket` | Ticket number |
| `Fare` | Ticket fare |
| `Cabin` | Cabin number |
| `Embarked` | Port of embarkation (C = Cherbourg, Q = Queenstown, S = Southampton) |

### Practice Goal

By completing the questions below, you will practice the same beginner-level Pandas concepts, including:

`read_csv()`, `head()`, `tail()`, `shape`, `columns`, `dtypes`, `info()`, `isnull()`, `isna()`, `sum()`, column selection, slicing, `loc`, `iloc`, `unique()`, `nunique()`, `value_counts()`, `max()`, filtering, `query()`, string methods, `apply()`, `lambda`, creating columns, `drop()`, `rename()`, `select_dtypes()`, `to_numpy()` and `to_csv()`.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **train.csv** into a DataFrame named `df`.

In [2]:
import pandas as pd
df=pd.read_csv(r"E:\Liha tech\LIHA tech Assignment\Pandas_Assignment\Assignment_no_13\Titanic.csv")

### Question 2
Display the first **5 rows** of the dataset.

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Question 3
Display the last **5 rows** of the dataset.

In [4]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

### Question 4
Find the total number of **rows and columns** in the dataset.

In [5]:
df.shape

(891, 12)

### Question 5
Display all the **column names** present in the dataset.

In [6]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

### Question 6
Display the **data type of each column**.

In [7]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## 2. Checking Missing Values

### Question 8
Check the number of **null values in each column** using `isnull()`.

In [9]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### Question 9
Check the number of missing values again using `isna()`.

In [10]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### Question 10
Display only the columns that have **at least one missing value** (hint: store `df.isnull().sum()` in a variable and filter it).

In [11]:
df.isnull().any(axis=0).sum()
onenull=df.isnull().sum()
df.loc[:,onenull>0]

      Age Cabin Embarked
0    22.0   NaN        S
1    38.0   C85        C
2    26.0   NaN        S
3    35.0  C123        S
4    35.0   NaN        S
..    ...   ...      ...
886  27.0   NaN        S
887  19.0   B42        S
888   NaN   NaN        S
889  26.0  C148        C
890  32.0   NaN        Q

[891 rows x 3 columns]

### Question 11
Find the **percentage of missing values** in the **Cabin** column.

In [12]:
df["Cabin"].isnull().sum()

np.int64(687)

## 3. Selecting Data

### Question 12
Select and display only the **Name** column.

In [13]:
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

### Question 13
Select and display the **Name, Sex, and Survived** columns.

In [14]:
df[["Name","Sex","Survived"]]

                                                  Name     Sex  Survived
0                              Braund, Mr. Owen Harris    male         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female         1
2                               Heikkinen, Miss. Laina  female         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female         1
4                             Allen, Mr. William Henry    male         0
..                                                 ...     ...       ...
886                              Montvila, Rev. Juozas    male         0
887                       Graham, Miss. Margaret Edith  female         1
888           Johnston, Miss. Catherine Helen "Carrie"  female         0
889                              Behr, Mr. Karl Howell    male         1
890                                Dooley, Mr. Patrick    male         0

[891 rows x 3 columns]

### Question 14
Display the first **10 rows** using DataFrame slicing.

In [15]:
df.loc[0:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S

### Question 15
Using `iloc`, display the first **5 rows and first 4 columns**.

### Question 16
Using `loc`, display rows **0 to 4** for the columns **Name, Sex, and Age**.

In [16]:
df.loc[0:4,["Name","Sex","Age"]]

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

## 4. Exploring Unique Values

### Question 17
Display all the **unique values** from the **Embarked** column.

In [17]:
df["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

### Question 18
Find the total number of **unique values** in the **Embarked** column.

In [18]:
df["Embarked"].nunique()

3

### Question 19
Display all the **unique values** from the **Pclass** column.

In [19]:
df["Pclass"].unique()

array([3, 1, 2])

### Question 20
Count how many records belong to each **Sex** value using `value_counts()`.

In [20]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

### Question 21
Count how many records belong to each **Survived** value using `value_counts()`.

In [21]:
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

## 5. Basic Analysis and Filtering

### Question 22
Find the **maximum value** available in the **Fare** column.

In [22]:
df["Fare"].max()

512.3292

### Question 23
Display all rows whose **Fare** is greater than **100**.

In [23]:
df[df["Fare"]>100]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss. Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss. Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss. Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss. Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss. Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss. Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss. Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss. Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss. Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss. Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss. Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

### Question 24
Display all rows whose **Age** is greater than **60**.

In [24]:
df[df["Age"]>60]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

### Question 25
Display only the rows where **Sex** is **female**.

In [25]:
df[df["Sex"]=="female"]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

### Question 26
Using `query()`, display all passengers travelling in **Pclass 1**.

In [26]:
df.query("Pclass==1")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

### Question 27
Display passengers who **survived** (`Survived` equal to 1) and travelled in **Pclass 3**.

In [27]:
df.query("Pclass==3 and Survived==1")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S
855,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,NaN,S
858,859,1,3,"Baclini, Mrs. Solomon (Latifa Qurban)",female,24.0,0,3,2666,19.2583,NaN,C
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C

## 6. Simple String Operations

### Question 28
Display all passengers whose **Name** contains the word `Miss`.

In [28]:
df.loc[df["Name"].str.contains("Miss",case=True),:]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

### Question 29
Convert the values in the **Sex** column to uppercase using a Pandas string method and display the result.

In [29]:
df["Sex"]=df["Sex"].str.upper()
df["Sex"]

0        MALE
1      FEMALE
2      FEMALE
3      FEMALE
4        MALE
        ...
886      MALE
887    FEMALE
888    FEMALE
889      MALE
890      MALE
Name: Sex, Length: 891, dtype: object

## 7. Creating and Modifying Columns

### Question 30
Create a new column called **Age Group**. Store `Child` when `Age` is less than 18; otherwise store `Adult`. Use `apply()` with a `lambda` function.

In [30]:
df["Age_group"]=df["Age"].apply(lambda x: "Child" if x<18 else "Adult")

### Question 31
Display the first **10 rows** after creating the **Age Group** column.

In [31]:
df["Age_group"].head(10)

0    Adult
1    Adult
2    Adult
3    Adult
4    Adult
5    Adult
6    Adult
7    Child
8    Adult
9    Child
Name: Age_group, dtype: object

### Question 32
Remove the **Age Group** column using `drop()`.

In [32]:
# df.drop(columns=["Age_group"])
# df.drop(columns=["Age_group"],inplace=True)
df["Age_group"]

0      Adult
1      Adult
2      Adult
3      Adult
4      Adult
       ...
886    Adult
887    Adult
888    Adult
889    Adult
890    Adult
Name: Age_group, Length: 891, dtype: object

### Question 33
Rename the column **SibSp** to **Siblings_Spouses**.

In [33]:
df.columns=df.columns.str.replace("SibSp","Siblings_Spouses")
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'Siblings_Spouses', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked',
       'Age_group'],
      dtype='object')

## 8. Conversion and Export

### Question 34
Select and display only the **numeric columns** from the dataset using `select_dtypes()`.

In [34]:
df.select_dtypes(int)

     PassengerId  Survived  Pclass  Siblings_Spouses  Parch
0              1         0       3                 1      0
1              2         1       1                 1      0
2              3         1       3                 0      0
3              4         1       1                 1      0
4              5         0       3                 0      0
..           ...       ...     ...               ...    ...
886          887         0       2                 0      0
887          888         1       1                 0      0
888          889         0       3                 1      2
889          890         1       1                 0      0
890          891         0       3                 0      0

[891 rows x 5 columns]

### Question 35
Convert the first **10 rows** of the DataFrame into a NumPy array using `to_numpy()`.

In [35]:
df.loc[0:10].to_numpy()

array([[1, 0, 3, 'Braund, Mr. Owen Harris', 'MALE', 22.0, 1, 0,
        'A/5 21171', 7.25, nan, 'S', 'Adult'],
       [2, 1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
        'FEMALE', 38.0, 1, 0, 'PC 17599', 71.2833, 'C85', 'C', 'Adult'],
       [3, 1, 3, 'Heikkinen, Miss. Laina', 'FEMALE', 26.0, 0, 0,
        'STON/O2. 3101282', 7.925, nan, 'S', 'Adult'],
       [4, 1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
        'FEMALE', 35.0, 1, 0, '113803', 53.1, 'C123', 'S', 'Adult'],
       [5, 0, 3, 'Allen, Mr. William Henry', 'MALE', 35.0, 0, 0,
        '373450', 8.05, nan, 'S', 'Adult'],
       [6, 0, 3, 'Moran, Mr. James', 'MALE', nan, 0, 0, '330877', 8.4583,
        nan, 'Q', 'Adult'],
       [7, 0, 1, 'McCarthy, Mr. Timothy J', 'MALE', 54.0, 0, 0, '17463',
        51.8625, 'E46', 'S', 'Adult'],
       [8, 0, 3, 'Palsson, Master. Gosta Leonard', 'MALE', 2.0, 3, 1,
        '349909', 21.075, nan, 'S', 'Child'],
       [9, 1, 3, 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
        'FEMALE', 27.0, 0, 2, '347742', 11.1333, nan, 'S', 'Adult'],
       [10, 1, 2, 'Nasser, Mrs. Nicholas (Adele Achem)', 'FEMALE', 14.0,
        1, 0, '237736', 30.0708, nan, 'C', 'Child'],
       [11, 1, 3, 'Sandstrom, Miss. Marguerite Rut', 'FEMALE', 4.0, 1, 1,
        'PP 9549', 16.7, 'G6', 'S', 'Child']], dtype=object)

### Question 36
Convert all column names to lowercase using `columns.str.lower()`.

In [36]:
df.columns=df.columns.str.lower()

### Question 37
Save the DataFrame as a new CSV file named **Titanic_Practice_Output.csv** using `to_csv()` without saving the index.

In [37]:
df.to_csv("Titanic_Beginner_Pandas_Practice_Output.csv",index=False)

## End of Practice

Try to solve each question independently.  
The main goal is to become comfortable with **basic Pandas syntax and DataFrame operations** before moving to more advanced EDA topics such as grouping, aggregation, pivot tables, correlation, and visualization.