# Exploratory Data Analysis and Insights on Bank Marketing Using Pandas

### Beginner-to-Intermediate Pandas Practice Notebook

This notebook is designed for students who are learning how to explore customer and campaign data using **Pandas**.

The exercises begin with basic DataFrame operations and gradually introduce:

- Loading and inspecting a CSV file
- Checking data quality
- Exploring categorical customer information
- Selecting, filtering, and sorting records
- Grouping and aggregating campaign results
- Creating derived columns
- Examining correlations
- Creating basic visualizations
- Exporting an analyzed DataFrame

## About the Dataset

The **BankMarketing.csv** dataset contains **4,521 customer-contact records** from direct-marketing campaigns conducted by a Portuguese banking institution.

It contains **17 columns**:

| Group | Example columns | Description |
|---|---|---|
| Customer profile | `age`, `job`, `marital`, `education` | Basic customer characteristics |
| Financial information | `credit_default`, `balance`, `housing_loan`, `personal_loan` | Account balance and loan information |
| Current contact | `contact_type`, `contact_day`, `contact_month`, `duration_seconds` | Information about the latest campaign contact |
| Campaign history | `campaign_contacts`, `days_since_previous_contact`, `previous_contacts`, `previous_outcome` | Current and previous contact history |
| Outcome | `subscribed` | Whether the customer subscribed to a term deposit (`yes` or `no`) |

### Important Observation

This assignment uses the smaller 10% sample supplied by the repository. It is suitable for classroom practice and remains small enough for a Git repository.

Some categorical columns contain the text value `unknown`. This is a recorded category, not a standard Pandas missing value. The value `-1` in `days_since_previous_contact` indicates that the customer was not previously contacted.

The original semicolon-separated file was converted to a standard comma-separated CSV, and abbreviated column names were replaced with descriptive names. The records were not otherwise changed.

**Source:** [UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/222/bank+marketing)  
**License:** CC BY 4.0

## Learning Goal

By completing this assignment, you will practice a complete beginner-to-intermediate Pandas workflow. You will compare customer groups, explore campaign outcomes, create useful indicators, and summarize relationships between balances, contacts, and subscriptions.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **BankMarketing.csv** into a DataFrame named `df`.

In [1]:
import pandas as pd
df=pd.read_csv(r"E:\Liha tech\LIHA tech Assignment\Pandas_Assignment\Assignment_no_9\BankMarketing.csv")

### Question 2
Display the first **5 rows** of the dataset.

In [2]:
df.head()

,age,job,marital,education,credit_default,balance,housing_loan,personal_loan,contact_type,contact_day,contact_month,duration_seconds,campaign_contacts,days_since_previous_contact,previous_contacts,previous_outcome,subscribed
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

### Question 3
Display the last **5 rows** of the dataset.

In [3]:
df.tail()

,age,job,marital,education,credit_default,balance,housing_loan,personal_loan,contact_type,contact_day,contact_month,duration_seconds,campaign_contacts,days_since_previous_contact,previous_contacts,previous_outcome,subscribed
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

### Question 4
Find the total number of **rows and columns** in the dataset.

In [4]:
df.shape

(4521, 17)

### Question 5
Display all the **column names** in the dataset.

In [5]:
df.columns

Index(['age', 'job', 'marital', 'education', 'credit_default', 'balance',
       'housing_loan', 'personal_loan', 'contact_type', 'contact_day',
       'contact_month', 'duration_seconds', 'campaign_contacts',
       'days_since_previous_contact', 'previous_contacts', 'previous_outcome',
       'subscribed'],
      dtype='object')

### Question 6
Display the **data type of each column**.

In [6]:
df.dtypes

age                             int64
job                            object
marital                        object
education                      object
credit_default                 object
balance                         int64
housing_loan                   object
personal_loan                  object
contact_type                   object
contact_day                     int64
contact_month                  object
duration_seconds                int64
campaign_contacts               int64
days_since_previous_contact     int64
previous_contacts               int64
previous_outcome               object
subscribed                     object
dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   age                          4521 non-null   int64
 1   job                          4521 non-null   object
 2   marital                      4521 non-null   object
 3   education                    4521 non-null   object
 4   credit_default               4521 non-null   object
 5   balance                      4521 non-null   int64
 6   housing_loan                 4521 non-null   object
 7   personal_loan                4521 non-null   object
 8   contact_type                 4521 non-null   object
 9   contact_day                  4521 non-null   int64
 10  contact_month                4521 non-null   object
 11  duration_seconds             4521 non-null   int64
 12  campaign_contacts            4521 non-null   int64
 13  days_since_previous_contact  4521 non-null   int64
 14  previous_contacts            4521 non-null   int64
 15  previous_outcome             4521 non-null   object
 16  subscribed                   4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB

## 2. Checking Data Quality

### Question 8
Display the number of **missing values in each column**.

In [8]:
df.isnull().sum()

age                            0
job                            0
marital                        0
education                      0
credit_default                 0
balance                        0
housing_loan                   0
personal_loan                  0
contact_type                   0
contact_day                    0
contact_month                  0
duration_seconds               0
campaign_contacts              0
days_since_previous_contact    0
previous_contacts              0
previous_outcome               0
subscribed                     0
dtype: int64

### Question 9
Calculate the **total number of missing values** in the entire DataFrame.

In [9]:
df.isnull().sum().sum()

np.int64(0)

### Question 10
Check the number of **duplicate rows** in the dataset.

In [10]:
df.duplicated().sum()

np.int64(0)

### Question 11
Create a new DataFrame named `df_clean` with duplicate rows removed, then display its shape.

In [11]:
df_clean=df.drop_duplicates()

## 3. Selecting Rows and Columns

### Question 12
Select and display only the **subscribed** column from `df_clean`.

In [12]:
df_clean["subscribed"]

0       no
1       no
2       no
3       no
4       no
        ..
4516    no
4517    no
4518    no
4519    no
4520    no
Name: subscribed, Length: 4521, dtype: object

### Question 13
Select and display the **age, job, balance, housing_loan, campaign_contacts, and subscribed** columns.

In [13]:
df[["age","job","balance","housing_loan","campaign_contacts","subscribed"]]

      age            job  balance housing_loan  campaign_contacts subscribed
0      30     unemployed     1787           no                  1         no
1      33       services     4789          yes                  1         no
2      35     management     1350          yes                  1         no
3      30     management     1476          yes                  4         no
4      59    blue-collar        0          yes                  1         no
...   ...            ...      ...          ...                ...        ...
4516   33       services     -333          yes                  5         no
4517   57  self-employed    -3313          yes                  1         no
4518   57     technician      295           no                 11         no
4519   28    blue-collar     1137           no                  4         no
4520   44   entrepreneur     1136          yes                  2         no

[4521 rows x 6 columns]

### Question 14
Display the first **10 rows** using DataFrame slicing.

In [15]:
df.loc[0:9]

,age,job,marital,education,credit_default,balance,housing_loan,personal_loan,contact_type,contact_day,contact_month,duration_seconds,campaign_contacts,days_since_previous_contact,previous_contacts,previous_outcome,subscribed
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
5,35,management,single,tertiary,no,747,no,no,cellular,23,feb,141,2,176,3,failure,no
6,36,self-employed,married,tertiary,no,307,yes,no,cellular,14,may,341,1,330,2,other,no
7,39,technician,married,secondary,no,147,yes,no,cellular,6,may,151,2,-1,0,unknown,no
8,41,entrepreneur,married,tertiary,no,221,yes,no,unknown,14,may,57,2,-1,0,unknown,no
9,43,services,married,primary,no,-88,yes,yes,cellular,17,apr,313,1,147,2,failure,no

### Question 15
Using `iloc`, display the first **5 rows and first 6 columns**.

In [16]:
df_clean.iloc[0:5,0:6]

   age          job  marital  education credit_default  balance
0   30   unemployed  married    primary             no     1787
1   33     services  married  secondary             no     4789
2   35   management   single   tertiary             no     1350
3   30   management  married   tertiary             no     1476
4   59  blue-collar  married  secondary             no        0

### Question 16
Using `loc`, display rows **10 to 15** for the columns **age, job, education, balance, and subscribed**.

In [17]:
df.loc[10:15,["age","job","education","balance","subscribed"]]

    age          job  education  balance subscribed
10   39     services  secondary     9374         no
11   43       admin.  secondary      264         no
12   36   technician   tertiary     1109         no
13   20      student  secondary      502        yes
14   31  blue-collar  secondary      360         no
15   40   management   tertiary      194         no

## 4. Categories and Descriptive Statistics

### Question 17
Count the number of customers in each **job** category using `value_counts()`.

In [18]:
df["job"].value_counts()

job
management       969
blue-collar      946
technician       768
admin.           478
services         417
retired          230
self-employed    183
entrepreneur     168
unemployed       128
housemaid        112
student           84
unknown           38
Name: count, dtype: int64

### Question 18
Count the values in the **marital** and **education** columns.

In [19]:
df[["marital","education"]].value_counts()

marital   education
married   secondary    1427
          tertiary      727
single    secondary     609
married   primary       526
single    tertiary      468
divorced  secondary     270
          tertiary      155
married   unknown       117
divorced  primary        79
single    primary        73
          unknown        46
divorced  unknown        24
Name: count, dtype: int64

### Question 19
Count the `yes` and `no` values in the **subscribed** column.

In [20]:
df["subscribed"].value_counts()

subscribed
no     4000
yes     521
Name: count, dtype: int64

### Question 20
Count how many `unknown` values appear in the **education** and **previous_outcome** columns.

In [25]:
df[["education","previous_outcome"]].eq("unknown").sum()

education            187
previous_outcome    3705
dtype: int64

### Question 21
Display descriptive statistics for the numeric columns using `describe()`.

In [26]:
df.describe()

,age,balance,contact_day,duration_seconds,campaign_contacts,days_since_previous_contact,previous_contacts
count,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000
mean,41.170095,1422.657819,15.915284,263.961292,2.793630,39.766645,0.542579
std,10.576211,3009.638142,8.247667,259.856633,3.109807,100.121124,1.693562
min,19.000000,-3313.000000,1.000000,4.000000,1.000000,-1.000000,0.000000
25%,33.000000,69.000000,9.000000,104.000000,1.000000,-1.000000,0.000000
50%,39.000000,444.000000,16.000000,185.000000,2.000000,-1.000000,0.000000
75%,49.000000,1480.000000,21.000000,329.000000,3.000000,-1.000000,0.000000
max,87.000000,71188.000000,31.000000,3025.000000,50.000000,871.000000,25.000000

### Question 22
Calculate the **mean balance** and find the **minimum and maximum customer age**.

In [29]:
df['balance'].mean()
df["age"].agg(["min","max"])

min    19
max    87
Name: age, dtype: int64

## 5. Filtering and Sorting

### Question 23
Display all records where **subscribed is equal to `yes`**.

In [30]:
df[df["subscribed"]=="yes"]

,age,job,marital,education,credit_default,balance,housing_loan,personal_loan,contact_type,contact_day,contact_month,duration_seconds,campaign_contacts,days_since_previous_contact,previous_contacts,previous_outcome,subscribed
13,20,student,single,secondary,no,502,no,no,cellular,30,apr,261,1,-1,0,unknown,yes
30,68,retired,divorced,secondary,no,4189,no,no,telephone,14,jul,897,2,-1,0,unknown,yes
33,32,management,single,tertiary,no,2536,yes,no,cellular,26,aug,958,6,-1,0,unknown,yes
34,49,technician,married,tertiary,no,1235,no,no,cellular,13,aug,354,3,-1,0,unknown,yes
36,78,retired,divorced,primary,no,229,no,no,telephone,22,oct,97,1,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4494,26,technician,single,secondary,no,668,yes,no,unknown,28,may,576,3,-1,0,unknown,yes
4503,60,self-employed,married,primary,no,362,no,yes,cellular,29,jul,816,6,-1,0,unknown,yes
4504,42,blue-collar,single,secondary,no,1080,yes,yes,cellular,13,may,951,3,370,4,failure,yes
4505,32,admin.,single,secondary,no,620,yes,no,unknown,26,may,1234,3,-1,0,unknown,yes
4511,46,blue-collar,married,secondary,no,668,yes,no,unknown,15,may,1263,2,-1,0,unknown,yes

### Question 24
Display customers whose **balance is greater than 5,000**.

In [31]:
df[df['balance']>5000]

,age,job,marital,education,credit_default,balance,housing_loan,personal_loan,contact_type,contact_day,contact_month,duration_seconds,campaign_contacts,days_since_previous_contact,previous_contacts,previous_outcome,subscribed
10,39,services,married,secondary,no,9374,yes,no,unknown,20,may,273,1,-1,0,unknown,no
25,41,management,married,tertiary,no,5883,no,no,cellular,20,nov,182,2,-1,0,unknown,no
40,38,management,single,tertiary,no,11971,yes,no,unknown,17,nov,609,2,101,3,failure,no
62,48,management,married,tertiary,no,5887,no,no,cellular,13,aug,227,2,-1,0,unknown,no
64,56,admin.,married,secondary,no,16873,no,no,cellular,7,oct,223,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4441,38,management,married,tertiary,no,12877,no,no,unknown,17,jun,118,3,-1,0,unknown,no
4451,55,management,married,tertiary,no,6880,no,no,cellular,8,aug,353,2,-1,0,unknown,no
4453,35,blue-collar,married,secondary,no,5304,yes,no,cellular,20,nov,340,1,183,2,failure,no
4457,37,blue-collar,single,primary,no,6969,yes,no,unknown,20,may,412,1,-1,0,unknown,no
4489,45,management,married,tertiary,no,6945,no,no,cellular,5,aug,131,5,356,3,failure,no

### Question 25
Display customers younger than 30 who have a **housing loan**.

In [32]:
df.query("age>30 and housing_loan=='yes'")

,age,job,marital,education,credit_default,balance,housing_loan,personal_loan,contact_type,contact_day,contact_month,duration_seconds,campaign_contacts,days_since_previous_contact,previous_contacts,previous_outcome,subscribed
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
6,36,self-employed,married,tertiary,no,307,yes,no,cellular,14,may,341,1,330,2,other,no
7,39,technician,married,secondary,no,147,yes,no,cellular,6,may,151,2,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4514,38,blue-collar,married,secondary,no,1205,yes,no,cellular,20,apr,45,4,153,1,failure,no
4515,32,services,single,secondary,no,473,yes,no,cellular,7,jul,624,5,-1,0,unknown,no
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

### Question 26
Using `query()`, display successful subscriptions where **campaign_contacts is 2 or fewer**.

In [35]:
# df.query("sub")
df['subscribed']
df['campaign_contacts']
df.query("subscribed=='yes' and campaign_contacts<2")

,age,job,marital,education,credit_default,balance,housing_loan,personal_loan,contact_type,contact_day,contact_month,duration_seconds,campaign_contacts,days_since_previous_contact,previous_contacts,previous_outcome,subscribed
13,20,student,single,secondary,no,502,no,no,cellular,30,apr,261,1,-1,0,unknown,yes
36,78,retired,divorced,primary,no,229,no,no,telephone,22,oct,97,1,-1,0,unknown,yes
37,32,blue-collar,married,secondary,no,2089,yes,no,cellular,14,nov,132,1,-1,0,unknown,yes
38,33,management,married,secondary,no,3935,yes,no,cellular,6,may,765,1,342,2,failure,yes
49,61,admin.,married,unknown,no,4629,yes,no,cellular,27,jan,181,1,92,1,success,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4388,83,retired,divorced,primary,no,1097,no,no,telephone,5,mar,181,1,-1,0,unknown,yes
4416,32,blue-collar,single,secondary,no,811,yes,no,cellular,14,may,563,1,-1,0,unknown,yes
4423,45,management,single,tertiary,no,2048,yes,no,cellular,18,oct,310,1,804,1,failure,yes
4433,40,management,married,tertiary,no,-17,yes,yes,cellular,11,may,474,1,256,1,success,yes
4458,29,management,single,tertiary,no,572,no,no,cellular,16,dec,314,1,195,1,success,yes

### Question 27
Sort `df_clean` by **balance in descending order** and display the first 10 rows.

In [37]:
df_clean.sort_values(by="balance").head(10)

,age,job,marital,education,credit_default,balance,housing_loan,personal_loan,contact_type,contact_day,contact_month,duration_seconds,campaign_contacts,days_since_previous_contact,previous_contacts,previous_outcome,subscribed
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
2398,51,entrepreneur,married,secondary,yes,-2082,no,yes,cellular,28,jul,123,6,-1,0,unknown,no
2538,44,management,married,secondary,no,-1746,yes,no,unknown,20,jun,218,1,-1,0,unknown,no
856,49,technician,married,secondary,yes,-1680,yes,yes,unknown,27,jun,92,4,-1,0,unknown,no
3584,46,blue-collar,married,secondary,no,-1400,yes,no,telephone,6,may,309,3,355,4,failure,no
2072,44,management,single,tertiary,no,-1313,yes,yes,cellular,15,may,104,10,-1,0,unknown,no
1972,42,technician,married,secondary,no,-1310,yes,yes,unknown,28,may,162,1,-1,0,unknown,no
2599,52,management,married,tertiary,no,-1224,yes,no,cellular,7,may,253,4,-1,0,unknown,no
804,40,management,married,tertiary,no,-1212,yes,no,cellular,15,may,1259,2,333,18,failure,no
189,56,retired,married,secondary,no,-1206,yes,no,cellular,15,jun,382,2,-1,0,unknown,yes

### Question 28
Display the **5 records with the longest contact duration**.

In [ ]:
df.sort_values(by="duration_seconds",ascending=False).head()
df.sort_values(by="duration_seconds",ascending=True).tail()

,age,job,marital,education,credit_default,balance,housing_loan,personal_loan,contact_type,contact_day,contact_month,duration_seconds,campaign_contacts,days_since_previous_contact,previous_contacts,previous_outcome,subscribed
568,59,unemployed,married,primary,no,0,no,no,cellular,30,jan,3025,2,-1,0,unknown,no
3673,36,entrepreneur,married,tertiary,no,3057,no,no,unknown,16,jun,2769,4,-1,0,unknown,yes
4123,47,blue-collar,divorced,primary,no,126,yes,no,unknown,3,jun,2456,2,-1,0,unknown,yes
980,43,management,divorced,tertiary,no,388,yes,no,unknown,8,may,2087,2,-1,0,unknown,yes
3853,54,technician,married,secondary,no,-315,no,yes,cellular,10,jul,2029,1,-1,0,unknown,yes

## 6. Grouping and Aggregation

### Question 29
Calculate the **average balance for each job category**.

In [39]:
df.groupby("job")["balance"].mean()

job
admin.           1226.736402
blue-collar      1085.161734
entrepreneur     1645.125000
housemaid        2083.803571
management       1766.928793
retired          2319.191304
self-employed    1392.409836
services         1103.956835
student          1543.821429
technician       1330.996094
unemployed       1089.421875
unknown          1501.710526
Name: balance, dtype: float64

### Question 30
Calculate the **average contact duration for each subscription outcome**.

In [41]:
df.groupby("subscribed")["duration_seconds"].mean()

subscribed
no     226.347500
yes    552.742802
Name: duration_seconds, dtype: float64

### Question 31
Create a frequency table showing counts for each **marital status and subscription outcome** using `pd.crosstab()`.

In [47]:
# df[["marital","subscribed"]].pd.crosstab()
# crosstab dosent take df as a parameter it takes two params 1.column and 2.rows and calcultes the frequency for each row as per column
pd.crosstab(df["marital"],df["subscribed"])

df.groupby("marital")["subscribed"].value_counts()

marital   subscribed
divorced  no             451
          yes             77
married   no            2520
          yes            277
single    no            1029
          yes            167
Name: count, dtype: int64

### Question 32
For each education category, calculate the **minimum, maximum, and mean balance** using `agg()`.

In [52]:
df.groupby("education")["balance"].agg(["min","max","mean"])
df.columns

Index(['age', 'job', 'marital', 'education', 'credit_default', 'balance',
       'housing_loan', 'personal_loan', 'contact_type', 'contact_day',
       'contact_month', 'duration_seconds', 'campaign_contacts',
       'days_since_previous_contact', 'previous_contacts', 'previous_outcome',
       'subscribed'],
      dtype='object')

### Question 33
Determine which job category has the **largest number of successful subscriptions**.

In [58]:
# df.columns
#df.groupby("job")["subscribed"].value_counts()
pd.crosstab(df["job"],df["subscribed"]).idxmax()
# pd.crosstab(df["job"],df["subscribed"])

subscribed
no     blue-collar
yes     management
dtype: object

## 7. Creating and Modifying Columns

### Question 34
Create a new column named **balance_category** using `apply()` with a `lambda` function. Store `High` when `balance` is greater than or equal to 5,000; otherwise store `Regular`.

### Question 35
Create a column named **contacted_before**. Store `Yes` when `previous_contacts` is greater than zero; otherwise store `No`.

### Question 36
Create a new column named **duration_minutes** by converting `duration_seconds` into minutes.

## 8. Correlation, Visualization, and Export

### Question 37
Create a correlation matrix for **age, balance, duration_seconds, campaign_contacts, and previous_contacts**.

### Question 38
Create a **histogram** of customer balances with an appropriate title and axis labels.

### Question 39
Create a **bar chart** showing the number of `yes` and `no` subscription outcomes.

### Question 40
Save `df_clean` as **BankMarketing_Analyzed.csv** using `to_csv()` without saving the index.

## End of Practice

Try to solve each question independently before checking any reference material.

The main goal is to become comfortable with customer and campaign data before moving to classification models or more advanced marketing analysis.